// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/koetsuserizawa/wire_example/blogservice"
	"github.com/koetsuserizawa/wire_example/handlers"
	"github.com/koetsuserizawa/wire_example/userservice"
)

// Injectors from wire.go:

func initializeUserServiceHandler(dsn string) *handlers.UserServiceHandler {
	userDB := userservice.NewDb(dsn)
	userRepositoryInterface := userservice.NewUserRepository(userDB)
	userServiceInterface := userservice.NewUserService(userRepositoryInterface)
	userServiceHandler := handlers.NewUserServiceHandler(userServiceInterface)
	return userServiceHandler
}

func initializeBlogServiceHandler(dsn string) *handlers.BlogServiceHandler {
	articleDB := blogservice.NewDb(dsn)
	blogRepositoryInterface := blogservice.NewBlogRepository(articleDB)
	blogServiceInterface := blogservice.NewBlogService(blogRepositoryInterface)
	userDB := userservice.NewDb(dsn)
	userRepositoryInterface := userservice.NewUserRepository(userDB)
	userServiceInterface := userservice.NewUserService(userRepositoryInterface)
	blogServiceHandler := handlers.NewBlogServiceHandler(blogServiceInterface, userServiceInterface)
	return blogServiceHandler
}
